### ISSUE TITLE
Problem with filing gist 

### ISSUE THREAD

**Issue by phracek** [sclorg/rhscl-container-ci#74]
There is a problem with filing gist.

```bash
rhscl-images-varnish-rh-build] $ /bin/bash /tmp/jenkins879083978820992341.sh
+ CONTEXT=centos7
+ GIT_USER=sclorg
+ GIT_PROJECT=varnish-container
++ git rev-parse HEAD
+ GIT_COMMIT=b1e0546864c5eb4ca639c6f5fb889759af505e56
+ curl -Ss <URL_JENKINS>/job/rhscl-images-varnish-rh-build/14//consoleText
curl: (7) Failed connect to <URL_JENKINS>:443; Connection timed out
[EnvInject] - Injecting environment variables from a build step.
[EnvInject] - [ERROR] - The given properties file path 'build_log_url.prop' doesn't exist.
[EnvInject] - [ERROR] - Missing file path was resolved from pattern 'build_log_url.prop' .
[EnvInject] - [ERROR] - Problems occurs on injecting env vars as a build step: java.io.IOException: The given properties file path 'build_log_url.prop' doesn't exist.
Build step 'Execute Scripts' changed build result to FAILURE
Build step 'Execute Scripts' marked build as failure
[Set GitHub commit status (universal)] ERROR on repos [GHRepository@1b2052fe[nodeId=MDEwOlJlcG9zaXRvcnk1ODY1NDIwMQ==,description=Varnish HTTP Cache container images based on Red Hat Software Collections and intended for OpenShift and general usage. Users can choose between Red Hat Enterprise Linux, Fedora, and CentOS based images.,homepage=http://softwarecollections.org,name=varnish-container,fork=false,archived=false,size=106,milestones={},language=Shell,commits={},source=<null>,parent=<null>,isTemplate=<null>,url=https://api.github.com/repos/sclorg/varnish-container,id=58654201,nodeId=<null>,createdAt=2016-05-12T15:33:53Z,updatedAt=2021-04-14T08:35:14Z]] (sha:b1e0546) with context:rhscl-images-varnish-rh-build
Setting commit status on GitHub for https://github.com/sclorg/varnish-container/commit/b1e0546864c5eb4ca639c6f5fb889759af505e56
ERROR: Build step failed with exception
java.io.FileNotFoundException: https://api.github.com/repos/sclorg/varnish-container/statuses/b1e0546864c5eb4ca639c6f5fb889759af505e56
	at org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$OkHttpURLConnection.getInputStream(ObsoleteUrlFactory.java:490)
	at org.kohsuke.github.extras.okhttp3.ObsoleteUrlFactory$DelegatingHttpsURLConnection.getInputStream(ObsoleteUrlFactory.java:1204)
	at org.kohsuke.github.GitHubHttpUrlConnectionClient$HttpURLConnectionResponseInfo.bodyStream(GitHubHttpUrlConnectionClient.java:196)
	at org.kohsuke.github.GitHubResponse$ResponseInfo.getBodyAsString(GitHubResponse.java:326)
	at org.kohsuke.github.GitHubResponse.parseBody(GitHubResponse.java:91)
	at org.kohsuke.github.Requester.lambda$fetch$1(Requester.java:74)
	at org.kohsuke.github.GitHubClient.createResponse(GitHubClient.java:455)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:406)
Caused: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/sclorg/varnish-container/statuses/b1e0546864c5eb4ca639c6f5fb889759af505e56 {"message":"Validation Failed","errors":[{"resource":"Status","code":"custom","field":"target_url","message":"target_url must use http(s) scheme"}],"documentation_url":"https://docs.github.com/rest/reference/repos#create-a-commit-status"}
	at org.kohsuke.github.GitHubClient.interpretApiError(GitHubClient.java:486)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:414)
	at org.kohsuke.github.GitHubClient.sendRequest(GitHubClient.java:358)
	at org.kohsuke.github.Requester.fetch(Requester.java:74)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:1984)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:160)
Caused: org.jenkinsci.plugins.github.common.CombineErrorHandler$ErrorHandlingException
	at org.jenkinsci.plugins.github.common.CombineErrorHandler.handle(CombineErrorHandler.java:74)
	at org.jenkinsci.plugins.github.status.GitHubCommitStatusSetter.perform(GitHubCommitStatusSetter.java:164)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1905)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Set GitHub commit status (universal)' marked build as failure
Sending e-mails to: phracek@redhat.com hhorak@redhat.com
Finished: FAILURE
```

**Comment by phracek** [comment]
We do not use this repo at all. Jenkins is not used.
